### ISSUE TITLE
Where do you get the LLM model?

### ISSUE THREAD

**Issue by aladinoster** [tleers/llm-api-starterkit#1]
👋🏼 Interesting blog!

Thanks for the post, small question where do you get this binary file?

https://github.com/tleers/llm-api-starterkit/blob/18cd7b207752f6ca6b189dd8f805c3c7ba79c985/app/main_local_gpt_4_all.py#L15

**Comment by tleers** [comment]
Glad you liked it! If you surf to [gpt4all](https://gpt4all.io/index.html) and scroll down the main page, you'll find a drop-down with a list of models and an explanation, as well as a download button.

![Screenshot_20230603-130937.png](https://github.com/tleers/llm-api-starterkit/assets/13601709/3baafc36-e628-4a97-8816-d629e289033e)

**Comment by aladinoster** [comment]
Thanks a lot!
